// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBecPCGlPELssmLE-U-wT_2y0OcsxZufU4',
    appId: '1:248894815785:web:b6a004706af6460f6c6638',
    messagingSenderId: '248894815785',
    projectId: 'gearup-4a96d',
    authDomain: 'gearup-4a96d.firebaseapp.com',
    storageBucket: 'gearup-4a96d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaAH7Te1LQAZJR6bUoQEEWSPXaH-IC8_w',
    appId: '1:248894815785:android:8a71fdb9ac29fc0c6c6638',
    messagingSenderId: '248894815785',
    projectId: 'gearup-4a96d',
    storageBucket: 'gearup-4a96d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUlV4ijPURtO0hePlaMSi6LiUV70AJTk4',
    appId: '1:248894815785:ios:d7c69786345fc6af6c6638',
    messagingSenderId: '248894815785',
    projectId: 'gearup-4a96d',
    storageBucket: 'gearup-4a96d.firebasestorage.app',
    iosBundleId: 'com.salmaaa.gearUpApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUlV4ijPURtO0hePlaMSi6LiUV70AJTk4',
    appId: '1:248894815785:ios:6d6eb1c0451d2ee86c6638',
    messagingSenderId: '248894815785',
    projectId: 'gearup-4a96d',
    storageBucket: 'gearup-4a96d.firebasestorage.app',
    iosBundleId: 'com.example.gearUpApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBecPCGlPELssmLE-U-wT_2y0OcsxZufU4',
    appId: '1:248894815785:web:46f53d234c6c56606c6638',
    messagingSenderId: '248894815785',
    projectId: 'gearup-4a96d',
    authDomain: 'gearup-4a96d.firebaseapp.com',
    storageBucket: 'gearup-4a96d.firebasestorage.app',
  );
}
